language: python
sudo: false

addons:
  apt:
    packages:
      - python-dev

python:
  - "2.7"

# add database

install:
  - pip install -Ur requirements.txt
  # add database migration

script:
  - make test
