version: '2'

services:

#  db:
#    image: postgres:9.5
#
#    environment:
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres

  rocket:
    build: .
    image: rocket
    container_name: rocket

    volumes:
      - .:/code/

#    depends_on:
#      - db

    ports:
      - "8000:8000"

    command: make dev
